### ISSUE TITLE
Where would you call w.Stop() to add a stop the worker?

### ISSUE THREAD

**Issue by shashank42** [nesv/nesv.github.io#12]

**Comment by nesv** [comment]
If you wanted to implement a graceful shutdown (e.g. triggered by an OS signal), in `func main`, you could call it from there.

Also, given that particular post was written ~6 years ago, there are some parts missing. For example, instead of making `Collector` an `http.HandlerFunc`, I would make it an `http.Handler` (with a `ServeHTTP`) method, and pass `WorkQueue` in as a struct field.

I would also, likely, make the `WorkQueue` its own type, and add `Start` and `Stop` methods to it.

I have written something similar that doesn't abstract so much over channels: https://github.com/nesv/workqueue. I would recommend using that, instead of trying to implement the details from [this blog post](https://nesv.github.io/golang/2014/02/25/worker-queues-in-go.html).
