### ISSUE TITLE
Why need a dispatcher?

### ISSUE THREAD

**Issue by jtakkala** [nesv/nesv.github.io#5]
Hi,

Why do you need a dispatcher in your worker queue article? I don't see the need for it as you can share a single channel amongst worker goroutines. The collector(s) can all have a reference to one work channel, and all worker goroutines as well can reference a single channel. All workers then select on that one work channel, and work is automatically allocated by the Go scheduler to the next available worker. 

The dispatcher architecture seems overly complicated to me. Or, am I missing something? Just wondering.

Thanks!

Jari

**Comment by nesv** [comment]
Hi Jari!

You're absolutely right. The dispatcher is somewhat unnecessary in the simple scenario, in the article.

The notion of the "dispatcher" came from a previous job, where the project required those of us working on it to have "messages", of multiple formats, go over the same serial connection. Note that this past project was not written in Go. We needed to read data off of the serial line as quickly as possible, and pass data-format-version-1 to the old system, and data-format-version-2 to the new system. We found it easiest to implement, and debug, when there was an intermediary "dispatcher", which provided a single spot to look at for the routing logic, and trap any errors that may have come from the collector, or the worker. It also kept the workers we wrote from becoming encumbered with that routing logic.

Ultimately, I think it depends on where you draw the line on responsibilities for each piece. The "version 2 worker" only had to contain code for doing the work it needed to, and the same logic extended to the worker for dealing with the "version 1" data.

Additionally, you could extend the dispatcher to throttle the throughput, in the event you have a clear bottleneck. In the example of the previous job, we had to re-send the version 1 data out over another serial line, to the old system.

I don't see this as being overly-complicated, only because there is a clear, logical division in what each piece does, and it allows you to extend, and modify the individual pieces, without having to touch the others.

Thank you very much, for asking! :smile:

**Comment by nesv** [comment]
Also, there isn't a one-size-fits-all for work distribution methods, and if nothing else, please consider the code in this article a starting point if you have never done something like this before.

**Comment by jtakkala** [comment]
Gotcha, I saw the other issue and reddit thread just after submitting this. I think it would be helpful if you explain in the example that this isn't the only way to do things, as it can lead new Go users to writing more complicated code than necessary. Up to you if you want to change that of course, just my two cents. :)
