### ISSUE TITLE
Getting values back out from Worker Queues

### ISSUE THREAD

**Issue by strataga** [nesv/nesv.github.io#6]
In reference to: http://nesv.github.io/golang/2014/02/25/worker-queues-in-go.html

Great article!

How would get a string value back out of the Worker (worker.go), from inside the go routine, to the Collector (collector.go). I want to respond the original http request with a value.

Your help would be greatly appreciated! Thanks!

~ Jason

**Comment by strataga** [comment]
So I got it working. But, I'm not sure if it's the best way to do it.

In my worker I get a base64 string of an image. I am going to eventually pass that string back to the original requester as a http response in collector.go.

work.go:

```
type WorkRequest struct {
  Url   string
  Delay time.Duration
  Img   chan string // new string channel
}
```

collector.go:

```
work := WorkRequest{url, delay, make(chan string)} // init of the string channel
go func() {
  fmt.Printf("work img -> %s\n", <-work.Img) // printing out base64 string as it comes back
}()
```

worker.go:

```
work.Img <- img // passing the base64 string along the channel
```

What do you think? Is there a better way to do it?

Thanks again!

~ Jason

**Comment by nesv** [comment]
Hi Jason! I'm glad you enjoyed the article. 

Your solution seems pretty clean, and since it works, I would say just go with it!

One thing I'm curious about, though: if you're looking to send responses back to the client, would a simpler approach be sufficient? The reason I ask, is because my article essentially outlines a really complicated semaphore, which has a central point for logic to figure out where a message should go to, but ultimately limits the amount of work that _can_ be done. If you're just looking to perform an HTTP request-response pattern, the approach in this article might be a little over-kill.

**Comment by strataga** [comment]
I am using your example to render webshots using casper.js through a golang exec call. So I really do need a worker queue instead of a normal request/response.

I have expanded your example to return a base64 image string from casper over the WorkRequest Img channel. Then I create and send back json response, with the base64 image string, to a given callback url.

It all works really, really well and it is extremely fast and efficient. It really just blows my mind how fast golang is. I can fire up thousands of workers and tens of thousands of requests and it runs like a dream; and I'm on an old dell laptop with Linux Mint.

Thanks again for your help.

~ Jason

**Comment by nesv** [comment]
You're most welcome, Jason! I'm glad my article helped. :smile:
